name: 'Build and Deploy Logic App'
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1.2
        with:
          dest: ${{ github.run_id }}.zip
          files: ./
      - uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ${{ github.run_id }}.zip
  Deploy:
    name: Deploy
    runs-on: self-hosted
    needs: [Build] 
    environment: dev
    steps:
     - uses: azure/login@v2
       with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
        enable-AzPSSession: true

     - uses: actions/download-artifact@master
       with:
        name: build-artifact
        path: build-art/

     - name: Deploy to Azure Logic App
       uses: Azure/functions-action@v1
       id: la
       with:
        app-name: ${{vars.LOGIC_APP_NAME}}
        package: build-art/${{ github.run_id }}.zip
       # publish-profile: ${{steps.laapp.outputs.profile}}