name: 'Build and Deploy Logic App'
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    environment: dev
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: Build Bicep templates
        run: |
          az bicep build infrastructure/bicep/01-foundation.bicep
          az bicep build infrastructure/bicep/02-main.bicep          

      - name: Swap connection.json
        run: |
          ls -al ./logic-app/
          mv logic-app/connections.json logic-app/connections.json.bak
          mv logic-app/connections.dev.json logic-app/connections.json
          ls -al ./logic-app/

      - name: Package Logic App
        uses: vimtor/action-zip@v1.2
        with:
          dest: ${{ github.run_id }}.zip
          files: ./logic-app/

      - uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ${{ github.run_id }}.zip
  Deploy:
    name: Deploy
    runs-on: self-hosted
    needs: [Build] 
    environment: dev
    steps:
     - uses: azure/login@v2
       with:
        #creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
        creds: '${{ secrets.AZURE_RBAC_CREDENTIALS }}'
        enable-AzPSSession: false

     - uses: actions/download-artifact@master
       with:
        name: build-artifact
        path: build-art/

     - name: Deploy main Bicep template
       run: |
          az deployment group create --name main-${{ github.run_id }} --resource-group $RESOURCE_GROUP_NAME --template-file ./bicep/02-main.bicep --parameters ./bicep/parameters/02-main.${{ env.ENV_NAME }}.bicepparam
  

     - name: Deploy to Azure Logic App
       uses: Azure/functions-action@v1
       id: la
       with:
        app-name: ${{vars.LOGIC_APP_NAME}}
        package: build-art/${{ github.run_id }}.zip